ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.daws88s.online
CATALOGUE_HOST: catalogue-dev.daws88s.online
REDIS_HOST: redis-dev.daws88s.online
USER_HOST: user-dev.daws88s.online
CART_HOST: cart-dev.daws88s.online
MYSQL_HOST: mysql-dev.daws88s.online
SHIPPING_HOST: shipping-dev.daws88s.online
RABBITMQ_HOST: rabbitmq-dev.daws88s.online
PAYMENT_HOST: payment-dev.daws88s.online