- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: starting and enabling mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: set up root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1