- name: adding roboshop user
  ansible.builtin.user:
    name: roboshop
    system: true
    shell: /sbin/nologin
    home: /app
    comment: "Roboshop system user"

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: delete "{{ component }}" zip file
  ansible.builtin.file:
    path: "/tmp/{{ component }}.zip"
    state: absent

- name: Download "{{ component }}" file
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: "/tmp/{{ component }}.zip"

- name: urarchive "{{ component }}"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes