- name: enable nodejs version 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: installing dependencies
  community.general.npm:
    path: /app